backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: 'Upload “{{path}}”'
    deleteMedia: 'Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "recipes"
    label: "Recipes"
    folder: "content/recipes"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Servings", name: "servings", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: Steps, name: steps, widget: list, fields: [{label: "Step", name: "step", widget: "text"}, {label: "Title", name: "title", widget: "string"}]}
